name: trunk

on:
  push:
    branches: [main, feature-*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git rev-parse --short HEAD
          git rev-parse --short HEAD^
      - uses: actions/github-script@v6
        id: infer
        with:
          script: |
            const childProcess = require("child_process");
            
            const branchName = '${{ github.ref_name }}';
            if (!branchName.startsWith('feature') && branchName !== 'main') {
              console.log("❗ The branch doesn't satisfy our naming requirements ❗");
              process.exit(1);
            }
            const branchType = branchName.split('-')[0];
            
            const modifiedDirectories = await new Promise((resolve, reject) => {
              childProcess.exec('git --no-pager diff --name-only HEAD^ HEAD', (err, stdout, stderr) => {
                if (err) {
                  console.error('Git command failed with output: ' + stderr);
                  reject(err);
                }
                const modifiedFiles = stdout.trim().split('\n');
                const modifiedDirectories = new Set(
                  modifiedFiles.map(path => path.split('/')[0])
                );
                resolve(modifiedDirectories);
              });
            });

            core.setOutput('branchType', branchType);
            core.setOutput('modifiedDirectories', modifiedDirectories);

            console.log(modifiedDirectories);
            console.table({ branchType, modifiedDirectories });
